export enum EOrderStatus {
  REGISTER_ORDER = 'REGISTER ORDER',
  CANCEL_BUY_CUSTOMER = 'CANCEL BUY CUSTOMER',
  CANCEL_BUY_GOAW = 'CANCEL BUY GOAW',
  CHECKED_PURCHASE_BILL = 'CHECKED PURCHASE BILL',
  PUCHASED_EC = 'PUCHASED EC',
  PRODUCT_ARRIVED_JP_OFFICE = 'PRODUCT ADDRIVED JP OFFICE',
  AGREE_FIX_PRICE = 'AGREE FIX PRICE',
  UNDER_SHIPPING = 'UNDER SHIPPING',
  PRODUCT_ARRIVED_VIETNAM_OFFICE = 'PRODUCT_ARRIVED_VIETNAM_OFFICE',
  ASK_DELIVERY_DATE_TIME = 'ASK DELIVERY DATETIME',
  DECIED_DELIVERY_DATE_TIME = 'DECIED DELIVERY DATE TIME',
  PRODUCT_ARRIVED_CUTOMER_HOUSE = 'PRODUCT ARRIVED CUTOMER HOUSE',
  COMPLETED = 'COMPLETED',
}
export enum EOrderType {
  PURCHASE_ORDER = 'PURCHASE ORDER',
  SHIP_ORDER = 'SHIP_ORDER',
}
