export const VALIDATE = {
  ID_NOT_EMPTY: 'Id cannot be blank',
  ID_NOT_INVALID: 'Id malformed',
  NAME_NOT_EMPTY: 'Name cannot be empty',
  NAME_NOT_INVALID: 'Name malformed',
  ID_CATEGORY_EMPTY: 'Product category id cannot be empty',
  ID_CATEGORY_INVALID: 'Product category id malformed',
  PRICE_EMPTY: 'Product price cannot be empty',
  PRICE_INVALID: 'Product price is not in the correct format',
  STATUS_EMPTY: 'Product status cannot be empty',
  STATUS_INVALID: 'Product status malformed',
  NUMBER_PRODUCT_EMPTY: 'Product quantity cannot be empty',
  NUMBER_PRODUCT_INVALID: 'Malformed product number',
  DESCRIPTION_EMPTY: 'Product description cannot be blank',
  DESCRIPTION_INVALID: 'Product description is not formatted properly',
  EMAIL_NOT_EMPTY: 'Email is not exist',
  EMAIL_INVALID: 'Invalid email',
  PHONE_NOT_EMPTY: 'Phone is not exist',
  PHONE_INVALID: 'Phone is not in the correct format',
  ADDRESS_NOT_EMPTY: 'Address is not exist',
  ADDRESS_INVALID: 'The address is not in the correct format',
};
