export const VALIDATE = {
  ID_NOT_EMPTY: 'Id cannot be blank',
  ID_NOT_INVALID: 'Id malformed',
  NAME_NOT_EMPTY: 'Name cannot be empty',
  NAME_NOT_INVALID: 'Name malformed',
  DESCRIPTION_NOT_EMPTY: 'Description cannot be empty',
  DESCRIPTION_NOT_INVALID: 'Description malformed',
  ID_CATEGORY_EMPTY: 'Product category id cannot be empty',
  ID_CATEGORY_INVALID: 'Product category id malformed',
  PRICE_EMPTY: 'Product price cannot be empty',
  PRICE_INVALID: 'Product price is not in the correct format',
  STATUS_EMPTY: 'Status cannot be empty',
  STATUS_INVALID: 'Status malformed',
  NUMBER_PRODUCT_EMPTY: 'Product quantity cannot be empty',
  NUMBER_PRODUCT_INVALID: 'Malformed product number',
  DESCRIPTION_EMPTY: 'Product description cannot be blank',
  DESCRIPTION_INVALID: 'Product description is not formatted properly',
  EMAIL_NOT_EMPTY: 'Email is not exist',
  EMAIL_INVALID: 'Invalid email',
  PHONE_NOT_EMPTY: 'Phone is not exist',
  PHONE_INVALID: 'Phone is not in the correct format',
  ADDRESS_NOT_EMPTY: 'Address is not exist',
  ADDRESS_INVALID: 'The address is not in the correct format',
  USERNAME_EMPTY: 'Username cannot be left blank',
  USERNAME_INVALID: 'Malformed username',
  PASSWORD_EMPTY: 'Password can not be blank',
  PASSWORD_INVALID: 'Incorrect password format',
  CUSTOMER_ID_EMPTY: 'Customer id cannot be left blank',
  CUSTOMER_ID_INVALID: 'Malformed customer id',
  QUANTITY_EMPTY: 'Quantity cannot be left blank',
  QUANTITY_INVALID: 'Malformed quantity',
  TOTAL_PRICE_EMPTY: 'Total price cannot be left blank',
  TOTAL_PRICE_INVALID: 'Total price is not in the correct format',
  PAYMENT_METHOD_EMPTY: 'Payment method cannot be left blank',
  PAYMENT_METHOD_INVALID: 'Malformed payment method',
  TRANSPORT_METHOD_EMPTY: 'Transport method cannot be left blank',
  TRANSPORT_METHOD_INVALID: 'Malformed transport method',
  DELIVERY_DATE_INVALID: 'Delivery date malformed',
};
